### ISSUE TITLE
SF: Unsupported flash IDs, manuf ff, jedec ffff, ext_jedec fffff

### ISSUE THREAD

**Issue by at1323at1323** [OpenNuvoton/NUC970_U-Boot_v2016.11#1]
Dears,

When boot from nandflash, i get some error:

U-Boot 2016.11-g2303ac8-dirty (Sep 27 2017 - 17:02:39 +0800)

CPU: NUC977
Board: NUC970
DRAM:  64 MiB
NAND:  128 MiB
In:    serial
Out:   serial
Err:   serial
Net:   emac
Hit any key to stop autoboot:  0

Loading from nand0, offset 0x200000
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    8718144 Bytes = 8.3 MiB
   Load Address: 00007fc0
   Entry Point:  00008000
## Booting kernel from Legacy Image at 00007fc0 ...
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    8718144 Bytes = 8.3 MiB
   Load Address: 00007fc0
   Entry Point:  00008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK

Starting kernel ...

SF: Unsupported flash IDs: manuf ff, jedec ffff, ext_jedec ffff
SPI probe failed.
### ERROR ### Please RESET the board ###

but used the nuvon (nuc970_U-Boot) is ok, 
have any idea for help me slove this question??

**Comment by yachen** [comment]
Is there a SPI flash on your hardware? If not or you don't need to access it from U-Boot, please disable SPI support.

**Comment by at1323at1323** [comment]
no, i had disabled SPI support.
