### ISSUE TITLE
Unconditional MDC handling

### ISSUE THREAD

**Issue by lightelf76** [OpenNuvoton/NUC970_U-Boot_v2016.11#14]
EMAC driver attempts to manipulate PHY registers unconditionally. It become a problem, if switch (like ksz8863rll) used instead of regular PHY. It's desirable to introduce CONFIG_ parameter to do avoid PHY registers touching. Do you want a patch for this modification?

**Comment by yachen** [comment]
Hi,

Does this patch affect existing users if CONFIG_ is not set?



Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by lightelf76** [comment]
No, it's not. 
CONFIG_NUC970_EMAC0_NO_MDC, if set skips some parts of EMAC0 driver and pin initialization (our board reuse MDC pins as GPIO for other purposes). Switch can be programmed via I2C, but it's not needed for U-Boot.

**Comment by yachen** [comment]
Hi,

Yes please submit the patch that skip MDC/MDIO control if CONFIG_NUC970_EMAC0_NO_MDC set.
We have other customers connect switch chip with EMAC. But I think they only use EMAC after enter Linux kernel. Thanks.


Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by lightelf76** [comment]
Done, please see pull request

**Comment by yachen** [comment]
Hi,

In Linux:
1. If you're using device tree, modify the device tree file to skip MDC and MDIO setting.
Otherwise you'll have to modify  drivers/pinctrl-nuc970.c to remove these pins from emac0_pins[] array.
2. Use ethtool to fix EMAC at 100F. 
3. Provide switch driver if kernel doesn't have driver for the switch you're using, 

Sincerely,

Yi-An Chen

**Comment by lightelf76** [comment]
Actually, it's not worked this way. EMAC0 interface just does not come up. nuc970_ether_probe() calls nuc970_mii_setup(), which itself tries to find any PHY (without success of course) and fails. Than  nuc970_ether_probe() fails also.

**Comment by yachen** [comment]
Ah, that’s right. Forgot the MII setup parts.
Other customers connecting with switch still use MDC/MDIO connecting with switch chip.
Does it work after remove the mii setup code?

Sincerely,

Yi-An Chen


===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by lightelf76** [comment]
Solution (for Linux) was to use Fixed PHY driver. I still need to implement proper support for switch, but it's OK as temporary solution. BTW, what is a current status of DeviceTree support? Is it mature or still "work in progress"?

**Comment by yachen** [comment]
Hi,

Yes, NUC970 kernel already supports device tree.


Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by yachen** [comment]
Hi,

That message means IBR cannot find boot image.
We also use GD25Q128B which works find on our DEV board. Can you check following items for me?

1.     Make sure boot image attribute is set as uBoot, no matter if it’s u-Boot or not.

2.     I compared the datasheet of GD25Q127C and GD25Q128B. The reset and read commands are the same, so IBR should be able to read the flash. But HOLD pin on GD25Q127C also has a extra function as RESET. Can you check this pin’s status during booting?

And by the way, NUC970 series doesn’t have ver. B 128 pin package. So what you’re using is a ver. C NUC976.

Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by lightelf76** [comment]
1. Of cause. NuWriter settings was exactly same for Winbond and Gigadevice cases
2. HOLD pin just tied to 3.3V with 10 kOhm resistor
3. :)) See attached photo from this board

**Comment by lightelf76** [comment]
1. Of cause the NuWriter settings was exactly same for Winbond and Gigadevice flash
2. HOLD pin tied to 3.3V with 10 kOhm resistor.
3. :))  
![nuc976 revb](https://user-images.githubusercontent.com/46067404/51751027-d6be8600-20c4-11e9-90b5-676d3fb8532d.jpg)

**Comment by yachen** [comment]
Hi,


I'll see if we can find some GD25Q127C sample to check this issue. Thanks.


Sincerely,


Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.
