### ISSUE TITLE
Bug in nuc970_eth.c

### ISSUE THREAD

**Issue by liuning587** [OpenNuvoton/NUC970_U-Boot_v2016.11#18]
`void init_rx_desc(void)
{
        int i;
        
        writel((unsigned int)&rx_desc[0], RXDLSA);
        rx_desc_ptr = &rx_desc[0];
        
        for(i = 0; i < RX_DESCRIPTOR_NUM; i++) {
                rx_desc[i].status1 = RXfOwnership_DMA;
                rx_desc[i].buf = (unsigned char *)net_rx_packets[i];
                rx_desc[i].status2 = 0;
                rx_desc[i].next = (struct eth_descriptor *)(&rx_desc[(i + 1) % TX_DESCRIPTOR_NUM]);                                
        }
        
        return;
}`

Line:157应该是RX_DESCRIPTOR_NUM
`
                rx_desc[i].next = (struct eth_descriptor *)(&rx_desc[(i + 1) % RX_DESCRIPTOR_NUM]);  
`

**Comment by yachen** [comment]
Fixed, thanks.

Sincerely,

Yi-An Chen
