### ISSUE TITLE
Mistake in driver i2c

### ISSUE THREAD

**Issue by jury093** [OpenNuvoton/NUC970_U-Boot_v2016.11#2]
drivers/i2c/nuc970_i2c.c:17:2: error: #endif without #if
make[1]: *** [drivers/i2c/nuc970_i2c.o] Error 1
make: *** [drivers/i2c] Error 2
make: *** Waiting for unfinished jobs....

**#include <common.h>

#if defined(CONFIG_NUC970_I2C)
#include <asm/io.h>
#include <asm-generic/gpio.h>
#endif
#endif**

remove, pls, last string - #endif

**Comment by yachen** [comment]
Hi @jury093 ,

Thanks for the feedback. Please pull again to fix this issue.


Sincerely,

Yi-An Chen
