### ISSUE TITLE
NUC980DK61Y UART9_RTS config

### ISSUE THREAD

**Issue by staunchheart** [OpenNuvoton/NUC970_U-Boot_v2016.11#20]
NUC980DK61Y 
PB.2   UART9_RTS    UART9 request to Send ouput pin
But make menuconfig
   NUC980 UART9 pin  selection
      (x) Rx:PB3, TX:PB1
      (  ) RX:PE8, TX:PE7
       (  ) RX:PE10, TX:PE12
       (  ) RX:PE6, TX:PE7, RTS:PE5, CTS:PE4

  can't config RTS:PB2

**Comment by yachen** [comment]
Hi,

We only open the config pin combinations supporting both CTS and RTS in Kconfig.
You can add 0x12 to uart9_0_pins[] arrary defined in pinctrl-nuc980.c to support PB2 RTS by select "(x) Rx:PB3, TX:PB1"


Sincerely,

Yi-An Chen

**Comment by staunchheart** [comment]
like this?
static const unsigned uart9_0_pins[] = {0x11, 0x13}; // tx, rx
static const unsigned uart9_1_pins[] = {0x12, 0x44}; // rts, cts
static const unsigned uart9_2_pins[] = {0x45, 0x44}; // rts, cts
static const unsigned uart9_3_pins[] = {0x47, 0x46}; // tx, rx
static const unsigned uart9_4_pins[] = {0x4C, 0x4A}; // tx, rx

**Comment by yachen** [comment]
No, like this:
-static const unsigned uart9_0_pins[] = {0x11, 0x13};
+static const unsigned uart9_0_pins[] = {0x11, 0x12, 0x13}; 

And keep the rest untouched.

**Comment by staunchheart** [comment]
TKS
