### ISSUE TITLE
watchdog on uboot

### ISSUE THREAD

**Issue by staunchheart** [OpenNuvoton/NUC970_U-Boot_v2016.11#21]
I use watchdog on NUC980DK61Yc
how can i update watchdog in uboot?

**Comment by yachen** [comment]
What setting do you want to update?

**Comment by staunchheart** [comment]
boot time more than 15 secend,
but watchdog 8secend time out .
when uboot runing but watchdog time out,system will start.
I try set the  env   "watchdog off" ，But it doesn't work！
so i think may be can Feed the watchdog  on uboot.

**Comment by yachen** [comment]
U-Boot reset WDT whenever possible. So you mean system reboot while kernel's booting?
WDT cannot turn off If it's enabled by power on setting.
May be you can use "watchdog on" setting, hw_watchdog_init() in nuc980_wdt.c will sets timeout interval to its max value.
