### ISSUE TITLE
I2C driver (can) broke relocation entries

### ISSUE THREAD

**Issue by lightelf76** [OpenNuvoton/NUC970_U-Boot_v2016.11#22]
I2C driver is initialized early at boot before relocation done and, because of this, must not use static/global variables (see comments at include/i2c.h line 546). Depending on the U-Boot configuration (modules compiled in) driver variables can (and I actually got this problem) overlap and destroy random part of relocation entries, making UBoot binary semi-functional.

**Comment by yachen** [comment]
Hi, The fix 1d5e322 is out. Many thanks for reporting this issue.
