### ISSUE TITLE
MAINTAINERS文件信息错误

### ISSUE THREAD

**Issue by qiubin2016** [OpenNuvoton/NUC970_U-Boot_v2016.11#26]
文件1：NUC970_U-Boot_v2016.11/board/nuvoton/nuc980/MAINTAINERS
文件1：NUC970_U-Boot_v2016.11/board/nuvoton/nuc970/MAINTAINERS
这两个文件里的信息没有修改成正确的信息。

**Comment by yachen** [comment]
Fixed. Thanks.
