### ISSUE TITLE
The console does not recognize too fast input

### ISSUE THREAD

**Issue by HetuSun** [OpenNuvoton/NUC970_U-Boot_v2016.11#30]
Hi Nuvoton,
    In the boot command line, there is no problem when we manually input through the keyboard, but garbled characters appear when we copy and paste。
    We suspect that it is caused by typing too fast. When experimenting, using the keyboard to quickly input information will also appear garbled。The conclusion is that the console cannot recognize too fast input
    How to modify uboot to fix this problem?
    
![image](https://user-images.githubusercontent.com/86333641/123023613-422dee80-d40a-11eb-8012-75e0b1231236.png)

**Comment by yachen** [comment]
Are you working on NUC970 or N9H30? Can you check if modify this line
https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11/blob/master/drivers/serial/serial_nuc970.c#L85
to
```c
UART0->LCR =0x03;
```
fix this issue? Thanks.

**Comment by HetuSun** [comment]
we working on NUC972
Incorporating that modification, the result remains unchanged. . .
![image](https://user-images.githubusercontent.com/86333641/123217033-b8128280-d4fc-11eb-96d2-33a4bcd79a46.png)

**Comment by yachen** [comment]
Can you attach your u-boot.bin here. Thanks

**Comment by HetuSun** [comment]
[u-boot.zip](https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11/files/6707035/u-boot.zip)
This is the uboot.bin that was incorporated and modified(LCR = 0x07 -> LCR = 0x03)

**Comment by yachen** [comment]
![image](https://user-images.githubusercontent.com/1320946/123218854-cc577f00-d4fe-11eb-80fc-cc0a73ecc13b.png)
Please check again, the LCR register value is still 7, not 3.

**Comment by HetuSun** [comment]
After I manually configure the registers, it can take effect
It may be that there are other places in uboot that have the configuration of this register, I will walk through the code again
Thank you so much!
![image](https://user-images.githubusercontent.com/86333641/123220202-4b998280-d500-11eb-8552-c6fdf5cecbd6.png)
