### ISSUE TITLE
NUC976 build uboot  add SPI configuration  appear error.

### ISSUE THREAD

**Issue by Venceplace** [OpenNuvoton/NUC970_U-Boot_v2016.11#31]

**Comment by yachen** [comment]
Do you need NAND control in U-Boot?

**Comment by Venceplace** [comment]
I don't need to use nand when compiling uboot. Can I close and exit nand support in menuconfig?However, after the menuconfig turns off the nand driver, many problems with nand initialization will be reported.

**Comment by yachen** [comment]
You also need to disable NAND related commands.  Try use nuc970_tomato_defconfig, this configuration disable NAND support and enable SPI support.
