### ISSUE TITLE
load kernal failed

### ISSUE THREAD

**Issue by junwushi** [OpenNuvoton/NUC970_U-Boot_v2016.11#4]
Spansion nand falsh type is:S34ML04G200TFI00, display below info:
U-Boot 2016.11-gd24f231-dirty (Mar 19 2018 - 11:36:16 +0800)

CPU: NUC972
Board: NUC970
DRAM:  64 MiB
NAND:  512 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   emac
Error: emac address not set.

Hit any key to stop autoboot:  0 

Loading from nand0, offset 0x200000
NAND read from offset 200000 failed -74
** Read error
## Booting kernel from Legacy Image at 00007fc0 ...
   Image Name:   Linux-3.10.108-01403-ge68da90fc9
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3130280 Bytes = 3 MiB
   Load Address: 00007fc0
   Entry Point:  00008000
   Verifying Checksum ... Bad Data CRC
ERROR: can't get kernel image!
=> 

and

**Comment by yachen** [comment]
Hi,

Can you use power on setting to set block size=2k, ecc=4 and test again, thanks.


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
that issue conditions is that set power on PA6/PA7 pin connect to earth for 2k page size,and  pa8/pa9 BCH pin  opened.

**Comment by yachen** [comment]
Hi,

I think the reason is because NuWriter tool and IBR (internal boot rom) treat this NAND as 2k+64 while u-boot (and kernel) can correctly identify it as a 2k+128 page size NAND. So while u-boot loads the kernel, it sees ECC un-correctable error and abort. But this issue should be fixed in c7a30813.

Are you testing with HEAD version of this repository?

Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
i  am just download it from repository  with the lastest version at  16/03/2018.

**Comment by yachen** [comment]
Hmmm. If you use latest NuWriter, please set power on setting to 2K page size and ECC 12.
Latest NuWriter does not support set page size only because IBR (Internal Boot ROM) doesn't support ONFI and setting page size or ECC only will confuse IBR for certain NAND types.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
No further response, close.
