### ISSUE TITLE
CONFIG_BOOTDELAY 不起作用

### ISSUE THREAD

**Issue by xray-bit** [OpenNuvoton/NUC970_U-Boot_v2016.11#43]
> CONFIG_BOOTDELAY:
> 
> Delay before automatcally running bootcmd;
> set to 0 to autoboot with no delay, but you can stop it by key input.
> set to -1 to disable autoboot.
> set to -2 to autoboot with no delay and not check for abort.

我把它设为 0 或者 -2，启动时依旧会有2秒的倒计时：`Hit any key to stop autoboot:  1`

defconfig 如下：
```
CONFIG_ARM=y
CONFIG_TARGET_NUC980_IOT=y
CONFIG_FIT=y
CONFIG_BOOTDELAY=-2
CONFIG_SYS_CONSOLE_OVERWRITE_ROUTINE=y
CONFIG_SYS_NO_FLASH=y
CONFIG_SPL=y
CONFIG_HUSH_PARSER=y
# CONFIG_CMD_IMLS is not set
# CONFIG_CMD_FLASH is not set
CONFIG_CMD_NAND=y
CONFIG_CMD_SF=y
CONFIG_CMD_SPI=y
# CONFIG_CMD_SETEXPR is not set
# CONFIG_CMD_NET is not set
# CONFIG_CMD_NFS is not set
CONFIG_CMD_TIMER=y
CONFIG_NAND_NUC980=y
CONFIG_SPI_FLASH=y
CONFIG_SPI_FLASH_BAR=y
CONFIG_SPI_NAND=y
# CONFIG_SPI_FLASH_USE_4K_SECTORS is not set
CONFIG_NUC980_CONSOLE=y
CONFIG_NUC980_SPI=y
CONFIG_REGEX=y
CONFIG_OF_LIBFDT=y
```

**Comment by ychuang3** [comment]
Please also update the  env.txt of u-boot.
Find  "bootdelay=" from env.txt.

**Comment by xray-bit** [comment]
> Please also update the env.txt of u-boot. Find "bootdelay=" from env.txt.

thx.
