### ISSUE TITLE
how to support device tree？

### ISSUE THREAD

**Issue by rainwonder** [OpenNuvoton/NUC970_U-Boot_v2016.11#5]

**Comment by rainwonder** [comment]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐ │  
  │ │                                      [*] Support Flattened Image Tree                                                                            │ │  
  │ │                                      [ ]   Support Flattened Image Tree within SPL                                                               │ │  
  │ │                                      [ ]   Display verbose messages on FIT boot                                                                  │ │  
  │ │                                      [ ] Select the best match for the kernel device tree                                                        │ │  
  │ │                                      [ ] Show verbose messages when FIT images fails                                                             │ │  
  │ │                                      ()  Extra Options (DEPRECATED)                                                                              │ │  
  │ │                                      [ ] Enable SPL loading U-Boot as a FIT                                                                      │ │  
  │ │                                      [ ] Enable SPL with DFU to load binaries to memory device                                                   │ │  
  │ │                                      [*] Enable arch_fixup_fdt() call
and then 

U-Boot 2016.11 (Aug 24 2018 - 14:23:53 +0800)

CPU: NUC972
Board: NUC970
DRAM:  64 MiB
NAND:  4863 MiB

can not start uboot

**Comment by rainwonder** [comment]
Hi

If I want to support the device tree to start the kernel, how should I modify the uboot and kernel?

Sincerely

**Comment by yachen** [comment]
Hi,

970's U-Boot driver does not support device tree. But U-Boot can still pass .dtb to kernel.
 
Enable following kernel options in menuconfig.
[*] Flattened Device Tree support 
[*] Support for the traditional ATAGS boot data passing

Enable following u-boot option
#define CONFIG_OF_LIBFDT
#define CONFIG_FIT


Sincerely,

Yi-An Chen

**Comment by rainwonder** [comment]
Hi，
 Yes, I have chosen these two options, but  can not start uboot.

**Comment by yachen** [comment]
Hmmm, my u-boot works fine with those two options enabled.
So your u-boot works fine without those two options?
What NAND flash are you using?

Sincerely,

Yi-An Chen

**Comment by rainwonder** [comment]
The NAND I used is H27U1G8F2B (Rev0.1) -nand flash 128M.

**Comment by yachen** [comment]
U-boot shows NAND capacity as 4351MB...
What is PA[6:9] power on setting status on your board? Please keep them as high.

**Comment by rainwonder** [comment]
My PA[6:9] is full of pins, I'm not sure whether it is high, I use a voltmeter to try

**Comment by yachen** [comment]
What board are you using?

**Comment by rainwonder** [comment]
![default](https://user-images.githubusercontent.com/16380254/44777480-5ba48280-abad-11e8-9237-f5dd24c4c628.png)

**Comment by yachen** [comment]
Please check SW35 on your board.

**Comment by rainwonder** [comment]
![default](https://user-images.githubusercontent.com/16380254/44777983-7dead000-abae-11e8-92e6-640b51c1abbd.png)
SW35 choose  on

**Comment by yachen** [comment]
If you re-build uboot with nuc970_defconfig, can it boot on your board?

**Comment by rainwonder** [comment]
Do not choose those two options?

**Comment by rainwonder** [comment]
use >make nuc970_defconfig
       >make all

**Comment by rainwonder** [comment]
But when I choose those two options, I can't start uboot.

**Comment by rainwonder** [comment]
![default](https://user-images.githubusercontent.com/16380254/44779192-64975300-abb1-11e8-8355-7bba71595e4d.png)
make menuconfig in uboot，i choose  those two options,

**Comment by yachen** [comment]
Un-select support flattened image tree within SPL and test again. You only need to trun on following two options.
#define CONFIG_OF_LIBFDT
#define CONFIG_FIT

And after restore default config, does your U-Boot shows correct NAND size?

**Comment by rainwonder** [comment]
yes，it shows correct NAND size，iwill try agin，I just need to modify include/configs/nuc970_evb.h ,and then make nuc970_defconfig,Do I not need to specify the address of *dtb in uboot?

**Comment by rainwonder** [comment]
Yeah, Two options were opened, but the compiler failed.
![default](https://user-images.githubusercontent.com/16380254/44781029-ee491f80-abb5-11e8-991b-41df7750132c.png)

Do I need to open some more options?

**Comment by yachen** [comment]
Please paste your .config file here.

**Comment by rainwonder** [comment]
#
# Automatically generated file; DO NOT EDIT.
# U-Boot 2016.11 Configuration
#
CONFIG_CREATE_ARCH_SYMLINK=y
# CONFIG_ARC is not set
CONFIG_ARM=y
# CONFIG_AVR32 is not set
# CONFIG_BLACKFIN is not set
# CONFIG_M68K is not set
# CONFIG_MICROBLAZE is not set
# CONFIG_MIPS is not set
# CONFIG_NDS32 is not set
# CONFIG_NIOS2 is not set
# CONFIG_OPENRISC is not set
# CONFIG_PPC is not set
# CONFIG_SANDBOX is not set
# CONFIG_SH is not set
# CONFIG_SPARC is not set
# CONFIG_X86 is not set
# CONFIG_XTENSA is not set
CONFIG_SYS_ARCH="arm"
CONFIG_SYS_CPU="arm926ejs"
CONFIG_SYS_SOC="nuc970"
CONFIG_SYS_VENDOR="nuvoton"
CONFIG_SYS_BOARD="nuc970"
CONFIG_SYS_CONFIG_NAME="nuc970_evb"

#
# ARM architecture
#
CONFIG_CPU_ARM926EJS=y
CONFIG_SYS_ARM_ARCH=5
CONFIG_SYS_CACHE_SHIFT_5=y
CONFIG_SYS_CACHELINE_SIZE=32
# CONFIG_SEMIHOSTING is not set
# CONFIG_SYS_L2CACHE_OFF is not set
# CONFIG_ENABLE_ARM_SOC_BOOT0_HOOK is not set
# CONFIG_ARCH_AT91 is not set
# CONFIG_TARGET_EDB93XX is not set
# CONFIG_TARGET_VCMA9 is not set
# CONFIG_TARGET_SMDK2410 is not set
# CONFIG_TARGET_ASPENITE is not set
# CONFIG_TARGET_GPLUGD is not set
# CONFIG_ARCH_DAVINCI is not set
# CONFIG_KIRKWOOD is not set
# CONFIG_ARCH_MVEBU is not set
# CONFIG_TARGET_DEVKIT3250 is not set
# CONFIG_TARGET_WORK_92105 is not set
# CONFIG_TARGET_MX25PDK is not set
CONFIG_TARGET_NUC970=y
# CONFIG_TARGET_NUC970_TOMATO is not set
# CONFIG_TARGET_NUC970_ETH2UART is not set
# CONFIG_TARGET_ZMX25 is not set
# CONFIG_TARGET_APF27 is not set
# CONFIG_TARGET_APX4DEVKIT is not set
# CONFIG_TARGET_XFI3 is not set
# CONFIG_TARGET_M28EVK is not set
# CONFIG_TARGET_MX23EVK is not set
# CONFIG_TARGET_MX28EVK is not set
# CONFIG_TARGET_MX23_OLINUXINO is not set
# CONFIG_TARGET_BG0900 is not set
# CONFIG_TARGET_SANSA_FUZE_PLUS is not set
# CONFIG_TARGET_SC_SPS_1 is not set
# CONFIG_ORION5X is not set
# CONFIG_TARGET_SPEAR300 is not set
# CONFIG_TARGET_SPEAR310 is not set
# CONFIG_TARGET_SPEAR320 is not set
# CONFIG_TARGET_SPEAR600 is not set
# CONFIG_TARGET_STV0991 is not set
# CONFIG_TARGET_X600 is not set
# CONFIG_TARGET_IMX31_PHYCORE is not set
# CONFIG_TARGET_MX31ADS is not set
# CONFIG_TARGET_MX31PDK is not set
# CONFIG_TARGET_WOODBURN is not set
# CONFIG_TARGET_WOODBURN_SD is not set
# CONFIG_TARGET_FLEA3 is not set
# CONFIG_TARGET_MX35PDK is not set
# CONFIG_ARCH_BCM283X is not set
# CONFIG_TARGET_VEXPRESS_CA15_TC2 is not set
# CONFIG_TARGET_VEXPRESS_CA5X2 is not set
# CONFIG_TARGET_VEXPRESS_CA9X4 is not set
# CONFIG_TARGET_BRXRE1 is not set
# CONFIG_TARGET_BRPPT1 is not set
# CONFIG_TARGET_DRACO is not set
# CONFIG_TARGET_THUBAN is not set
# CONFIG_TARGET_RASTABAN is not set
# CONFIG_TARGET_ETAMIN is not set
# CONFIG_TARGET_PXM2 is not set
# CONFIG_TARGET_RUT is not set
# CONFIG_TARGET_TI814X_EVM is not set
# CONFIG_TARGET_TI816X_EVM is not set
# CONFIG_TARGET_BCM23550_W1D is not set
# CONFIG_TARGET_BCM28155_AP is not set
# CONFIG_TARGET_BCMCYGNUS is not set
# CONFIG_TARGET_BCMNSP is not set
# CONFIG_ARCH_EXYNOS is not set
# CONFIG_ARCH_S5PC1XX is not set
# CONFIG_ARCH_HIGHBANK is not set
# CONFIG_ARCH_INTEGRATOR is not set
# CONFIG_ARCH_KEYSTONE is not set
# CONFIG_ARCH_MESON is not set
# CONFIG_ARCH_MX7 is not set
# CONFIG_ARCH_MX6 is not set
# CONFIG_ARCH_MX5 is not set
# CONFIG_TARGET_M53EVK is not set
# CONFIG_TARGET_MX51EVK is not set
# CONFIG_TARGET_MX53ARD is not set
# CONFIG_TARGET_MX53EVK is not set
# CONFIG_TARGET_MX53LOCO is not set
# CONFIG_TARGET_MX53SMD is not set
# CONFIG_OMAP34XX is not set
# CONFIG_OMAP44XX is not set
# CONFIG_OMAP54XX is not set
# CONFIG_AM43XX is not set
# CONFIG_AM33XX is not set
# CONFIG_ARCH_RMOBILE is not set
# CONFIG_TARGET_S32V234EVB is not set
# CONFIG_ARCH_SNAPDRAGON is not set
# CONFIG_ARCH_SOCFPGA is not set
# CONFIG_TARGET_CM_T43 is not set
# CONFIG_ARCH_SUNXI is not set
# CONFIG_TARGET_TS4800 is not set
# CONFIG_TARGET_VF610TWR is not set
# CONFIG_TARGET_COLIBRI_VF is not set
# CONFIG_TARGET_PCM052 is not set
# CONFIG_TARGET_BK4R1 is not set
# CONFIG_ARCH_ZYNQ is not set
# CONFIG_ARCH_ZYNQMP is not set
# CONFIG_TEGRA is not set
# CONFIG_TARGET_VEXPRESS64_AEMV8A is not set
# CONFIG_TARGET_VEXPRESS64_BASE_FVP is not set
# CONFIG_TARGET_VEXPRESS64_BASE_FVP_DRAM is not set
# CONFIG_TARGET_VEXPRESS64_JUNO is not set
# CONFIG_TARGET_LS2080A_EMU is not set
# CONFIG_TARGET_LS2080A_SIMU is not set
# CONFIG_TARGET_LS2080AQDS is not set
# CONFIG_TARGET_LS2080ARDB is not set
# CONFIG_TARGET_HIKEY is not set
# CONFIG_TARGET_LS1012AQDS is not set
# CONFIG_TARGET_LS1012ARDB is not set
# CONFIG_TARGET_LS1012AFRDM is not set
# CONFIG_TARGET_LS1021AQDS is not set
# CONFIG_TARGET_LS1021ATWR is not set
# CONFIG_TARGET_LS1043AQDS is not set
# CONFIG_TARGET_LS1043ARDB is not set
# CONFIG_TARGET_LS1046AQDS is not set
# CONFIG_TARGET_LS1046ARDB is not set
# CONFIG_TARGET_H2200 is not set
# CONFIG_TARGET_ZIPITZ2 is not set
# CONFIG_TARGET_COLIBRI_PXA270 is not set
# CONFIG_ARCH_UNIPHIER is not set
# CONFIG_STM32 is not set
# CONFIG_ARCH_ROCKCHIP is not set
# CONFIG_TARGET_THUNDERX_88XX is not set
# CONFIG_SPL_GPIO_SUPPORT is not set
# CONFIG_SPL_LIBCOMMON_SUPPORT is not set
# CONFIG_SPL_LIBGENERIC_SUPPORT is not set
# CONFIG_SPL_EXT_SUPPORT is not set
# CONFIG_SPL_FAT_SUPPORT is not set
# CONFIG_SPL_I2C_SUPPORT is not set
# CONFIG_SPL_LIBDISK_SUPPORT is not set
# CONFIG_SPL_MMC_SUPPORT is not set
# CONFIG_SPL_NAND_SUPPORT is not set
# CONFIG_SPL_POWER_SUPPORT is not set
# CONFIG_SPL_SERIAL_SUPPORT is not set
# CONFIG_SPL_DISPLAY_PRINT is not set
# CONFIG_SPL_ENV_SUPPORT is not set
# CONFIG_SPL_DRIVERS_MISC_SUPPORT is not set
# CONFIG_SPL_SPI_FLASH_SUPPORT is not set
# CONFIG_SPL_SPI_SUPPORT is not set
# CONFIG_SPL_WATCHDOG_SUPPORT is not set
CONFIG_NUC970=y
CONFIG_IDENT_STRING=""
# CONFIG_PRE_CONSOLE_BUFFER is not set
# CONFIG_VIDEO is not set
# CONFIG_SPL_YMODEM_SUPPORT is not set

#
# ARM debug
#
# CONFIG_DEBUG_LL is not set

#
# General setup
#
CONFIG_LOCALVERSION=""
CONFIG_LOCALVERSION_AUTO=y
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
# CONFIG_DISTRO_DEFAULTS is not set
# CONFIG_SYS_MALLOC_F is not set
CONFIG_EXPERT=y
CONFIG_SYS_MALLOC_CLEAR_ON_INIT=y
# CONFIG_TOOLS_DEBUG is not set
# CONFIG_PHYS_64BIT is not set

#
# Boot images
#
# CONFIG_FIT is not set
CONFIG_SYS_EXTRA_OPTIONS=""
# CONFIG_SPL_DFU_SUPPORT is not set
CONFIG_ARCH_FIXUP_FDT=y

#
# Boot timing
#
# CONFIG_BOOTSTAGE is not set
CONFIG_BOOTSTAGE_USER_COUNT=20
CONFIG_BOOTSTAGE_STASH_ADDR=0
CONFIG_BOOTSTAGE_STASH_SIZE=4096

#
# Boot media
#
# CONFIG_NAND_BOOT is not set
# CONFIG_ONENAND_BOOT is not set
# CONFIG_QSPI_BOOT is not set
# CONFIG_SATA_BOOT is not set
# CONFIG_SD_BOOT is not set
# CONFIG_SPI_BOOT is not set
CONFIG_BOOTDELAY=3

#
# Console
#
# CONFIG_CONSOLE_RECORD is not set
# CONFIG_SILENT_CONSOLE is not set
CONFIG_CONSOLE_MUX=y
CONFIG_SYS_CONSOLE_IS_IN_ENV=y
CONFIG_SYS_CONSOLE_OVERWRITE_ROUTINE=y
# CONFIG_SYS_CONSOLE_ENV_OVERWRITE is not set
# CONFIG_SYS_CONSOLE_INFO_QUIET is not set
# CONFIG_SYS_STDIO_DEREGISTER is not set
CONFIG_DEFAULT_FDT_FILE=""
CONFIG_SYS_NO_FLASH=y
# CONFIG_VERSION_VARIABLE is not set
CONFIG_DISPLAY_CPUINFO=y
CONFIG_DISPLAY_BOARDINFO=y

#
# SPL / TPL
#
CONFIG_SUPPORT_SPL=y
CONFIG_SPL=y
# CONFIG_SPL_SYS_MALLOC_SIMPLE is not set
# CONFIG_SPL_STACK_R is not set
# CONFIG_SPL_SEPARATE_BSS is not set
# CONFIG_SPL_CRYPTO_SUPPORT is not set
# CONFIG_SPL_HASH_SUPPORT is not set
# CONFIG_SPL_DMA_SUPPORT is not set
# CONFIG_SPL_FPGA_SUPPORT is not set
# CONFIG_SPL_MPC8XXX_INIT_DDR_SUPPORT is not set
# CONFIG_SPL_MTD_SUPPORT is not set
# CONFIG_SPL_MUSB_NEW_SUPPORT is not set
# CONFIG_SPL_NET_SUPPORT is not set
# CONFIG_SPL_NO_CPU_SUPPORT is not set
# CONFIG_SPL_NOR_SUPPORT is not set
# CONFIG_SPL_ONENAND_SUPPORT is not set
# CONFIG_SPL_OS_BOOT is not set
# CONFIG_SPL_POST_MEM_SUPPORT is not set
# CONFIG_SPL_SATA_SUPPORT is not set
# CONFIG_SPL_USBETH_SUPPORT is not set
# CONFIG_SPL_USB_HOST_SUPPORT is not set

#
# Command line interface
#
CONFIG_CMDLINE=y
CONFIG_HUSH_PARSER=y
CONFIG_SYS_PROMPT="=> "

#
# Autoboot options
#
CONFIG_AUTOBOOT=y
# CONFIG_AUTOBOOT_KEYED is not set

#
# FASTBOOT
#
# CONFIG_FASTBOOT is not set

#
# Commands
#

#
# Info commands
#
CONFIG_CMD_BDI=y
CONFIG_CMD_CONSOLE=y
# CONFIG_CMD_CPU is not set
# CONFIG_CMD_LICENSE is not set

#
# Boot commands
#
CONFIG_CMD_BOOTD=y
CONFIG_CMD_BOOTM=y
# CONFIG_CMD_BOOTZ is not set
CONFIG_CMD_ELF=y
CONFIG_CMD_GO=y
CONFIG_CMD_RUN=y
CONFIG_CMD_IMI=y
# CONFIG_CMD_IMLS is not set
CONFIG_CMD_XIMG=y

#
# Environment commands
#
# CONFIG_CMD_ASKENV is not set
CONFIG_CMD_EXPORTENV=y
CONFIG_CMD_IMPORTENV=y
CONFIG_CMD_EDITENV=y
# CONFIG_CMD_GREPENV is not set
CONFIG_CMD_SAVEENV=y
CONFIG_CMD_ENV_EXISTS=y

#
# Memory commands
#
CONFIG_CMD_MEMORY=y
CONFIG_CMD_CRC32=y
# CONFIG_LOOPW is not set
# CONFIG_CMD_MEMTEST is not set
# CONFIG_CMD_MX_CYCLIC is not set
# CONFIG_CMD_MEMINFO is not set

#
# Device access commands
#
CONFIG_CMD_LOADB=y
CONFIG_CMD_LOADS=y
# CONFIG_CMD_FLASH is not set
# CONFIG_CMD_ARMFLASH is not set
# CONFIG_CMD_MMC is not set
CONFIG_CMD_NAND=y
CONFIG_CMD_SF=y
CONFIG_CMD_SPI=y
# CONFIG_CMD_I2C is not set
CONFIG_CMD_USB=y
# CONFIG_CMD_DFU is not set
# CONFIG_CMD_USB_MASS_STORAGE is not set
CONFIG_CMD_FPGA=y
# CONFIG_CMD_GPIO is not set

#
# Shell scripting commands
#
CONFIG_CMD_ECHO=y
CONFIG_CMD_ITEST=y
CONFIG_CMD_SOURCE=y
# CONFIG_CMD_SETEXPR is not set

#
# Network commands
#
CONFIG_CMD_NET=y
# CONFIG_CMD_TFTPPUT is not set
# CONFIG_CMD_TFTPSRV is not set
# CONFIG_CMD_RARP is not set
CONFIG_CMD_DHCP=y
CONFIG_CMD_NFS=y
# CONFIG_CMD_MII is not set
CONFIG_CMD_PING=y
# CONFIG_CMD_CDP is not set
# CONFIG_CMD_SNTP is not set
# CONFIG_CMD_DNS is not set
# CONFIG_CMD_LINK_LOCAL is not set

#
# Misc commands
#
# CONFIG_CMD_CACHE is not set
# CONFIG_CMD_TIME is not set
CONFIG_CMD_MISC=y
CONFIG_CMD_TIMER=y
# CONFIG_CMD_QFW is not set

#
# Power commands
#

#
# Security commands
#

#
# Firmware commands
#

#
# Filesystem commands
#
# CONFIG_CMD_EXT2 is not set
# CONFIG_CMD_EXT4 is not set
CONFIG_CMD_FAT=y
# CONFIG_CMD_FS_GENERIC is not set
CONFIG_CMD_UBI=y
CONFIG_SUPPORT_OF_CONTROL=y

#
# Device Tree Control
#
# CONFIG_OF_CONTROL is not set
CONFIG_NET=y
# CONFIG_NET_RANDOM_ETHADDR is not set
# CONFIG_NETCONSOLE is not set
CONFIG_NET_TFTP_VARS=y
CONFIG_BOOTP_PXE_CLIENTARCH=0x15
CONFIG_BOOTP_VCI_STRING="U-Boot.arm"

#
# Device Drivers
#

#
# Generic Driver Options
#
# CONFIG_DM is not set
# CONFIG_ADC is not set
# CONFIG_ADC_EXYNOS is not set
# CONFIG_ADC_SANDBOX is not set
# CONFIG_BLOCK_CACHE is not set

#
# Clock
#
# CONFIG_CPU is not set

#
# Hardware crypto devices
#
# CONFIG_FSL_CAAM is not set

#
# Demo for driver model
#

#
# DFU support
#

#
# DMA Support
#
# CONFIG_TI_EDMA3 is not set

#
# FPGA support
#
# CONFIG_FPGA_XILINX is not set

#
# GPIO Support
#
CONFIG_NUC970_GPIO=y

#
# I2C support
#
# CONFIG_SYS_I2C_DW is not set
# CONFIG_CROS_EC_KEYB is not set

#
# LED Support
#

#
# Mailbox Controller Support
#

#
# Memory Controller drivers
#

#
# Multifunction device drivers
#
# CONFIG_CROS_EC is not set
# CONFIG_FSL_SEC_MON is not set
# CONFIG_MXC_OCOTP is not set
# CONFIG_NUVOTON_NCT6102D is not set
# CONFIG_PCA9551_LED is not set
# CONFIG_WINBOND_W83627 is not set

#
# MMC Host controller Support
#
# CONFIG_NUC970_MMC is not set

#
# MTD Support
#

#
# NAND Device Support
#
# CONFIG_NAND_DENALI is not set
# CONFIG_NAND_VF610_NFC is not set
# CONFIG_NAND_PXA3XX is not set
# CONFIG_NAND_ARASAN is not set
CONFIG_NAND_NUC970=y

#
# Generic NAND options
#
# CONFIG_SYS_NAND_U_BOOT_LOCATIONS is not set
# CONFIG_SPL_NAND_DENALI is not set

#
# SPI Flash Support
#
CONFIG_SPI_FLASH=y
CONFIG_SPI_FLASH_BAR=y
# CONFIG_SPI_FLASH_ATMEL is not set
# CONFIG_SPI_FLASH_EON is not set
# CONFIG_SPI_FLASH_GIGADEVICE is not set
# CONFIG_SPI_FLASH_MACRONIX is not set
# CONFIG_SPI_FLASH_SPANSION is not set
# CONFIG_SPI_FLASH_STMICRO is not set
# CONFIG_SPI_FLASH_SST is not set
# CONFIG_SPI_FLASH_WINBOND is not set
# CONFIG_SPI_NAND is not set
CONFIG_SPI_FLASH_USE_4K_SECTORS=y
# CONFIG_SPI_FLASH_MTD is not set

#
# UBI support
#
CONFIG_MTD_UBI=y
CONFIG_MTD_UBI_WL_THRESHOLD=4096
CONFIG_MTD_UBI_BEB_LIMIT=20
# CONFIG_MTD_UBI_FASTMAP is not set
# CONFIG_PHYLIB is not set
CONFIG_NETDEVICES=y
# CONFIG_E1000 is not set
# CONFIG_ETH_DESIGNWARE is not set
# CONFIG_ETHOC is not set
# CONFIG_RTL8139 is not set
# CONFIG_RTL8169 is not set
CONFIG_NUC970_ETH=y
CONFIG_NUC970_EMAC0=y
CONFIG_NUC970_PHY_ADDR=1
# CONFIG_PCI is not set
# CONFIG_MVEBU_COMPHY_SUPPORT is not set

#
# Pin controllers
#

#
# Power
#

#
# Power Domain Support
#

#
# Remote Processor drivers
#

#
# Reset Controller Support
#

#
# Real Time Clock
#

#
# Serial drivers
#
# CONFIG_DEBUG_UART is not set
# CONFIG_DEBUG_UART_SKIP_INIT is not set
# CONFIG_ATMEL_USART is not set
# CONFIG_FSL_LPUART is not set
# CONFIG_MVEBU_A3700_UART is not set
# CONFIG_SYS_NS16550 is not set
CONFIG_NUC970_CONSOLE=y

#
# Sound support
#
# CONFIG_SOUND is not set

#
# SPI Support
#
# CONFIG_FSL_ESPI is not set
# CONFIG_FSL_QSPI is not set
# CONFIG_TI_QSPI is not set
CONFIG_NUC970_SPI=y

#
# SPMI support
#

#
# System reset device drivers
#
# CONFIG_DM_THERMAL is not set

#
# Timer Support
#

#
# TPM support
#
CONFIG_USB=y

#
# USB Host Controller Drivers
#
CONFIG_USB_HOST=y
# CONFIG_USB_XHCI_HCD is not set
CONFIG_USB_EHCI_HCD=y
CONFIG_USB_EHCI=y
CONFIG_USB_EHCI_NUC970=y
# CONFIG_USB_OHCI_HCD is not set
# CONFIG_USB_UHCI_HCD is not set

#
# MUSB Controller Driver
#
# CONFIG_USB_MUSB_HOST is not set
# CONFIG_USB_MUSB_GADGET is not set

#
# ULPI drivers
#

#
# USB peripherals
#
CONFIG_USB_STORAGE=y
# CONFIG_USB_KEYBOARD is not set
# CONFIG_USB_GADGET is not set

#
# Graphics support
#

#
# TrueType Fonts
#
# CONFIG_VIDEO_VESA is not set
# CONFIG_VIDEO_LCD_ANX9804 is not set
# CONFIG_VIDEO_LCD_SSD2828 is not set
# CONFIG_VIDEO_MVEBU is not set
CONFIG_CONSOLE_SCROLL_LINES=1
CONFIG_LCD=y
CONFIG_NUC970_LCD=y
CONFIG_NUC970_WATCHDOG=y
# CONFIG_PHYS_TO_BUS is not set

#
# File systems
#

#
# Library routines
#
# CONFIG_CC_OPTIMIZE_LIBS_FOR_SPEED is not set
CONFIG_HAVE_PRIVATE_LIBGCC=y
CONFIG_USE_PRIVATE_LIBGCC=y
CONFIG_SYS_HZ=1000
# CONFIG_USE_TINY_PRINTF is not set
CONFIG_REGEX=y
# CONFIG_LIB_RAND is not set
# CONFIG_CMD_DHRYSTONE is not set
# CONFIG_RSA is not set

#
# Hashing Support
#
# CONFIG_SHA1 is not set
# CONFIG_SHA256 is not set
# CONFIG_SHA_HW_ACCEL is not set

#
# Compression Support
#
# CONFIG_LZ4 is not set
# CONFIG_ERRNO_STR is not set
# CONFIG_OF_LIBFDT is not set
# CONFIG_OF_LIBFDT_OVERLAY is not set
# CONFIG_SPL_OF_LIBFDT is not set

#
# System tables
#
# CONFIG_UNIT_TEST is not set

**Comment by rainwonder** [comment]
[config.txt](https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11/files/2332125/config.txt)

**Comment by rainwonder** [comment]
This is my  .config

**Comment by rainwonder** [comment]
After I try again,still see the error reported.No need to answer some config option  when I build my config.
i show you my command to build uboot，
>vim include/configs/nuc970_evb.h ->  add #define CONFIG_OF_LIBFDT #define CONFIG_FIT
>make nuc970_defconfig
>make ARCH=arm CROSS_COMPILE=arm-linux- all

**Comment by yachen** [comment]
Enable those two options in header file seems break some dependency rule.
Please enable them with menuconfig. Anyway, attached is my config file.
[config_ok.txt](https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11/files/2334447/config_ok.txt)

**Comment by rainwonder** [comment]
Oh,There is no need to add #define CONFIG_OF_LIBFDT #define CONFIG_FIT to inlcude/configs/nuc970_evb.h. just make menuconfig is ok.
![default](https://user-images.githubusercontent.com/16380254/44839917-84428000-ac72-11e8-8d40-a050f5c7f877.png)
![default](https://user-images.githubusercontent.com/16380254/44839953-98867d00-ac72-11e8-8b06-e9bc1eda23c4.png)

But didn't start uboot whith nand,

**Comment by yachen** [comment]
Can you attach the u-boot.bin that failed to boot up here?

**Comment by rainwonder** [comment]
[u-boot.txt](https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11/files/2335452/u-boot.txt)
this is my uboot.bin

**Comment by rainwonder** [comment]
Yeah，it is ok！
Thanks a lot for your help.

**Comment by yachen** [comment]
How do you set the FDT address? Have you try to pass the address to bootm command?

**Comment by rainwonder** [comment]
command ->: fdt addr 0x600000

**Comment by rainwonder** [comment]
Hi，
     What is the problem of my command

**Comment by yachen** [comment]
nothing's wrong. You need to load the dtb file to the offset first.

=> nand read 0x600000 0x200000 0x100000

NAND read: device 0 offset 0x200000, size 0x100000
 1048576 bytes read: OK
=> fdt addr 0x600000
=>

**Comment by rainwonder** [comment]
I have download the dtb and kernel，then just use command 
=>bootm 0x7fc0 
![default](https://user-images.githubusercontent.com/16380254/45020139-acf6bb00-b060-11e8-95c5-6bba7c452748.png)
spi pin is off.
The nuc972.dts in kernel needs to be modified .

**Comment by yachen** [comment]
That message's from U-Boot. Please rebuid U-Boot with SPI disabled if you don't need it.

**Comment by rainwonder** [comment]
I have disabled spi-flash and rebuid  u-boot, but the same error occurred during startup

**Comment by yachen** [comment]
Please check your .config file make make sure SPI related stuffs are disabled.

**Comment by rainwonder** [comment]
![default](https://user-images.githubusercontent.com/16380254/45025352-cfdb9c00-b06d-11e8-9f1c-5be5dca0d45c.png)
dtb is not correct？

**Comment by yachen** [comment]
You need to pass the dtb address to kernel.
