### ISSUE TITLE
Bug in nuc970_i2c.c

### ISSUE THREAD

**Issue by lightelf76** [OpenNuvoton/NUC970_U-Boot_v2016.11#6]
Functions nuc970_i2c_read() and nuc970_i2c_write() uses hardcoded value **2** instead of parameter **alen**
See fix at: https://github.com/lightelf76/NUC970_U-Boot_v2016.11/commit/e0b8499462d74649b69651b962ef509eb5acaa43?diff=unified

**Comment by yachen** [comment]
Hi,

Could you send a pull request? Thanks.


Sincerely,

Yi-An Chen

**Comment by lightelf76** [comment]
Done! I am novice in git, so my apologies for any mixup

**Comment by yachen** [comment]
Pulled with a commit-id append in the commit message. Thanks.
